// packages/angular-workspace/projects/connect-angular/src/lib/provider-button/provider-button.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import {
    GoogleIconSvg,
    OutlookIconSvg,
    ZoomIconSvg,
    ICloudIconSvg
} from '@pyas/connect';

export const ICONS: Record<string,string> = {
    google:    GoogleIconSvg,
    microsoft: OutlookIconSvg,
    zoom:      ZoomIconSvg,
    icloud:    ICloudIconSvg
};

@Component({
    standalone: true,
    imports: [CommonModule],
    selector: 'connect-provider-button',
    templateUrl: './provider-button.component.html',
    styleUrls: ['./provider-button.component.css'],
    changeDetection: ChangeDetectionStrategy.Default
})
export class ProviderButtonComponent {
    /** one of 'google' | 'microsoft' | 'zoom' | 'icloud' */
    @Input() provider!: keyof typeof ICONS;
    @Input() label!: string;
    @Input() showLabel = true;

    /** emits provider key when clicked */
    @Output() select = new EventEmitter<typeof this.provider>();

    safeIconSvg!: SafeHtml;

    constructor(private sanitizer: DomSanitizer) {}

    ngOnChanges() {
      // whenever provider changes, re-sanitize
      this.safeIconSvg = this.sanitizer.bypassSecurityTrustHtml(ICONS[this.provider] || '');
    }

    onClick() {
      this.select.emit(this.provider);
    }
}

<button class="pyas-provider-button" (click)="onClick()">
  <span class="icon" [innerHTML]="safeIconSvg"></span>

  <span *ngIf="showLabel" class="label">{{ label }}</span>

  <span class="arrow">
        <span class="arrow">
            <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                class="arrow-icon"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="m8.25 4.5 7.5 7.5-7.5 7.5"
            />
            </svg>
        </span>
    </span>
</button>

// packages/connect-vue/src/components/ProviderButton.vue
<template>
  <button class="pyas-provider-button" @click="$emit('click')">
    <span class="icon" v-html="icon"></span>
    <span v-if="showLabel" class="label">{{ label }}</span>
    <span class="arrow">
        <span class="arrow">
            <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                class="arrow-icon"
            >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="m8.25 4.5 7.5 7.5-7.5 7.5"
            />
            </svg>
        </span>
    </span>
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { getProviderIcon } from '../utils';

const props = defineProps({
  /** one of 'google' | 'microsoft' | 'zoom' | 'icloud' */
  provider: { type: String as () => 'google'|'microsoft'|'zoom'|'icloud', required: true },
  /** Button label text */
  label:    { type: String, required: true },
  /** Show/hide the text label */
  showLabel:{ type: Boolean, default: true },
});

const emit = defineEmits<{
  (e: 'click'): void;
}>();

const icon = computed(() => getProviderIcon(props.provider) || '');
</script>
